### ISSUE TITLE
Link to Github project for review

### ISSUE THREAD

**Issue by devalibello** [wwwdrt/group-capstone-1#42]
https://github.com/users/wwwdrt/projects/5

There are two people on the team

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @wwwdrt, and @devalibello👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] Most of the task cards don't have team members assigned to them, Please make sure to assign team members to all cards according to students A and B.
![image](https://github.com/wwwdrt/group-capstone-1/assets/83803414/bffe27bc-2254-447e-a98f-928395b85e4c)

Example: 
![image](https://github.com/wwwdrt/group-capstone-1/assets/83803414/cf19673c-3308-40db-94eb-8b62fb12dac1)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tufoinnkuo10** [comment]
## Status: Approved :heavy_check_mark:

Hi @Team

Your project is complete! Great job making the changes🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- work well shared
- Board well set


<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
